/**
 * Common emoji shortcodes for `:` autocomplete (Notion / Slack style).
 * Keep this list practical — search matches name + aliases.
 */

export interface EmojiEntry {
  /** Primary shortcode without colons, e.g. "smile" */
  name: string
  emoji: string
  /** Extra search tokens */
  aliases?: string[]
}

export const EMOJI_CATALOG: EmojiEntry[] = [
  // Smileys
  { name: 'grinning', emoji: '😀', aliases: ['happy', 'smile'] },
  { name: 'smiley', emoji: '😃', aliases: ['happy'] },
  { name: 'smile', emoji: '😄', aliases: ['happy'] },
  { name: 'grin', emoji: '😁' },
  { name: 'laughing', emoji: '😆', aliases: ['satisfied'] },
  { name: 'sweat_smile', emoji: '😅' },
  { name: 'rofl', emoji: '🤣', aliases: ['rolling'] },
  { name: 'joy', emoji: '😂', aliases: ['tears', 'lol'] },
  { name: 'slightly_smiling_face', emoji: '🙂', aliases: ['smile'] },
  { name: 'upside_down_face', emoji: '🙃' },
  { name: 'wink', emoji: '😉' },
  { name: 'blush', emoji: '😊' },
  { name: 'innocent', emoji: '😇', aliases: ['angel', 'halo'] },
  { name: 'heart_eyes', emoji: '😍', aliases: ['love'] },
  { name: 'star_struck', emoji: '🤩' },
  { name: 'kissing_heart', emoji: '😘' },
  { name: 'kissing', emoji: '😗' },
  { name: 'relaxed', emoji: '☺️', aliases: ['smile'] },
  { name: 'yum', emoji: '😋' },
  { name: 'stuck_out_tongue', emoji: '😛' },
  { name: 'stuck_out_tongue_winking_eye', emoji: '😜' },
  { name: 'zany_face', emoji: '🤪' },
  { name: 'raised_eyebrow', emoji: '🤨' },
  { name: 'monocle_face', emoji: '🧐' },
  { name: 'nerd_face', emoji: '🤓', aliases: ['nerd', 'glasses'] },
  { name: 'sunglasses', emoji: '😎', aliases: ['cool'] },
  { name: 'partying_face', emoji: '🥳', aliases: ['party', 'celebrate'] },
  { name: 'smirk', emoji: '😏' },
  { name: 'unamused', emoji: '😒' },
  { name: 'roll_eyes', emoji: '🙄' },
  { name: 'grimacing', emoji: '😬' },
  { name: 'lying_face', emoji: '🤥' },
  { name: 'relieved', emoji: '😌' },
  { name: 'pensive', emoji: '😔' },
  { name: 'sleepy', emoji: '😪' },
  { name: 'drooling_face', emoji: '🤤' },
  { name: 'sleeping', emoji: '😴', aliases: ['zzz'] },
  { name: 'mask', emoji: '😷' },
  { name: 'face_with_thermometer', emoji: '🤒', aliases: ['sick'] },
  { name: 'face_with_head_bandage', emoji: '🤕' },
  { name: 'nauseated_face', emoji: '🤢' },
  { name: 'vomiting_face', emoji: '🤮' },
  { name: 'sneezing_face', emoji: '🤧' },
  { name: 'hot_face', emoji: '🥵' },
  { name: 'cold_face', emoji: '🥶' },
  { name: 'woozy_face', emoji: '🥴' },
  { name: 'dizzy_face', emoji: '😵' },
  { name: 'exploding_head', emoji: '🤯', aliases: ['mindblown'] },
  { name: 'cowboy_hat_face', emoji: '🤠' },
  { name: 'partying', emoji: '🥳' },
  { name: 'disguised_face', emoji: '🥸' },
  { name: 'sunglasses_cool', emoji: '😎' },
  { name: 'confused', emoji: '😕' },
  { name: 'worried', emoji: '😟' },
  { name: 'slightly_frowning_face', emoji: '🙁' },
  { name: 'frowning', emoji: '☹️' },
  { name: 'open_mouth', emoji: '😮' },
  { name: 'hushed', emoji: '😯' },
  { name: 'astonished', emoji: '😲' },
  { name: 'flushed', emoji: '😳' },
  { name: 'pleading_face', emoji: '🥺', aliases: ['please'] },
  { name: 'frowning_face', emoji: '😦' },
  { name: 'anguished', emoji: '😧' },
  { name: 'fearful', emoji: '😨' },
  { name: 'cold_sweat', emoji: '😰' },
  { name: 'disappointed_relieved', emoji: '😥' },
  { name: 'cry', emoji: '😢', aliases: ['sad', 'tear'] },
  { name: 'sob', emoji: '😭', aliases: ['cry'] },
  { name: 'scream', emoji: '😱', aliases: ['shock'] },
  { name: 'confounded', emoji: '😖' },
  { name: 'persevere', emoji: '😣' },
  { name: 'disappointed', emoji: '😞' },
  { name: 'sweat', emoji: '😓' },
  { name: 'weary', emoji: '😩' },
  { name: 'tired_face', emoji: '😫' },
  { name: 'yawning_face', emoji: '🥱' },
  { name: 'triumph', emoji: '😤' },
  { name: 'rage', emoji: '😡', aliases: ['angry', 'mad'] },
  { name: 'angry', emoji: '😠' },
  { name: 'cursing_face', emoji: '🤬' },
  { name: 'smiling_imp', emoji: '😈', aliases: ['devil'] },
  { name: 'imp', emoji: '👿' },
  { name: 'skull', emoji: '💀', aliases: ['dead'] },
  { name: 'skull_and_crossbones', emoji: '☠️' },
  { name: 'poop', emoji: '💩', aliases: ['hankey', 'shit'] },
  { name: 'clown_face', emoji: '🤡', aliases: ['clown'] },
  { name: 'ogre', emoji: '👹' },
  { name: 'goblin', emoji: '👺' },
  { name: 'ghost', emoji: '👻' },
  { name: 'alien', emoji: '👽' },
  { name: 'space_invader', emoji: '👾' },
  { name: 'robot', emoji: '🤖', aliases: ['robot_face'] },
  { name: 'smiley_cat', emoji: '😺' },
  { name: 'smile_cat', emoji: '😸' },
  { name: 'joy_cat', emoji: '😹' },
  { name: 'heart_eyes_cat', emoji: '😻' },
  { name: 'smirk_cat', emoji: '😼' },
  { name: 'kissing_cat', emoji: '😽' },
  { name: 'scream_cat', emoji: '🙀' },
  { name: 'crying_cat_face', emoji: '😿' },
  { name: 'pouting_cat', emoji: '😾' },

  // Gestures / people
  { name: 'wave', emoji: '👋', aliases: ['hello', 'hi', 'bye'] },
  { name: 'raised_back_of_hand', emoji: '🤚' },
  { name: 'hand', emoji: '✋', aliases: ['raised_hand'] },
  { name: 'vulcan_salute', emoji: '🖖' },
  { name: 'ok_hand', emoji: '👌' },
  { name: 'pinched_fingers', emoji: '🤌' },
  { name: 'pinching_hand', emoji: '🤏' },
  { name: 'v', emoji: '✌️', aliases: ['peace', 'victory'] },
  { name: 'crossed_fingers', emoji: '🤞' },
  { name: 'love_you_gesture', emoji: '🤟' },
  { name: 'metal', emoji: '🤘', aliases: ['horns'] },
  { name: 'call_me_hand', emoji: '🤙' },
  { name: 'point_left', emoji: '👈' },
  { name: 'point_right', emoji: '👉' },
  { name: 'point_up_2', emoji: '👆' },
  { name: 'point_down', emoji: '👇' },
  { name: 'point_up', emoji: '☝️' },
  { name: 'thumbsup', emoji: '👍', aliases: ['+1', 'yes', 'like'] },
  { name: 'thumbsdown', emoji: '👎', aliases: ['-1', 'no', 'dislike'] },
  { name: 'fist', emoji: '✊' },
  { name: 'facepunch', emoji: '👊', aliases: ['punch'] },
  { name: 'left_facing_fist', emoji: '🤛' },
  { name: 'right_facing_fist', emoji: '🤜' },
  { name: 'clap', emoji: '👏', aliases: ['applause'] },
  { name: 'raised_hands', emoji: '🙌', aliases: ['hooray'] },
  { name: 'open_hands', emoji: '👐' },
  { name: 'palms_up_together', emoji: '🤲' },
  { name: 'handshake', emoji: '🤝' },
  { name: 'pray', emoji: '🙏', aliases: ['please', 'thanks', 'hope'] },
  { name: 'writing_hand', emoji: '✍️' },
  { name: 'nail_care', emoji: '💅' },
  { name: 'selfie', emoji: '🤳' },
  { name: 'muscle', emoji: '💪', aliases: ['flex', 'strong'] },
  { name: 'mechanical_arm', emoji: '🦾' },
  { name: 'mechanical_leg', emoji: '🦿' },
  { name: 'leg', emoji: '🦵' },
  { name: 'foot', emoji: '🦶' },
  { name: 'ear', emoji: '👂' },
  { name: 'nose', emoji: '👃' },
  { name: 'brain', emoji: '🧠' },
  { name: 'eyes', emoji: '👀', aliases: ['look'] },
  { name: 'eye', emoji: '👁️' },
  { name: 'tongue', emoji: '👅' },
  { name: 'lips', emoji: '👄' },
  { name: 'baby', emoji: '👶' },
  { name: 'child', emoji: '🧒' },
  { name: 'boy', emoji: '👦' },
  { name: 'girl', emoji: '👧' },
  { name: 'adult', emoji: '🧑' },
  { name: 'man', emoji: '👨' },
  { name: 'woman', emoji: '👩' },
  { name: 'older_man', emoji: '👴' },
  { name: 'older_woman', emoji: '👵' },
  { name: 'person_frowning', emoji: '🙍' },
  { name: 'person_pouting', emoji: '🙎' },
  { name: 'no_good', emoji: '🙅' },
  { name: 'ok_person', emoji: '🙆' },
  { name: 'information_desk_person', emoji: '💁' },
  { name: 'raising_hand', emoji: '🙋' },
  { name: 'deaf_person', emoji: '🧏' },
  { name: 'bow', emoji: '🙇' },
  { name: 'facepalm', emoji: '🤦', aliases: ['face_palm'] },
  { name: 'shrug', emoji: '🤷' },
  { name: 'health_worker', emoji: '🧑‍⚕️' },
  { name: 'student', emoji: '🧑‍🎓' },
  { name: 'teacher', emoji: '🧑‍🏫' },
  { name: 'judge', emoji: '🧑‍⚖️' },
  { name: 'farmer', emoji: '🧑‍🌾' },
  { name: 'cook', emoji: '🧑‍🍳' },
  { name: 'mechanic', emoji: '🧑‍🔧' },
  { name: 'factory_worker', emoji: '🧑‍🏭' },
  { name: 'office_worker', emoji: '🧑‍💼' },
  { name: 'scientist', emoji: '🧑‍🔬' },
  { name: 'technologist', emoji: '🧑‍💻', aliases: ['coder', 'developer', 'programmer'] },
  { name: 'singer', emoji: '🧑‍🎤' },
  { name: 'artist', emoji: '🧑‍🎨' },
  { name: 'pilot', emoji: '🧑‍✈️' },
  { name: 'astronaut', emoji: '🧑‍🚀' },
  { name: 'firefighter', emoji: '🧑‍🚒' },
  { name: 'police_officer', emoji: '👮', aliases: ['cop'] },
  { name: 'detective', emoji: '🕵️' },
  { name: 'guard', emoji: '💂' },
  { name: 'ninja', emoji: '🥷' },
  { name: 'construction_worker', emoji: '👷' },
  { name: 'prince', emoji: '🤴' },
  { name: 'princess', emoji: '👸' },
  { name: 'person_with_turban', emoji: '👳' },
  { name: 'person_with_veil', emoji: '👰' },
  { name: 'pregnant_woman', emoji: '🤰' },
  { name: 'breast_feeding', emoji: '🤱' },
  { name: 'angel', emoji: '👼' },
  { name: 'santa', emoji: '🎅' },
  { name: 'mrs_claus', emoji: '🤶' },
  { name: 'superhero', emoji: '🦸' },
  { name: 'supervillain', emoji: '🦹' },
  { name: 'mage', emoji: '🧙', aliases: ['wizard', 'witch'] },
  { name: 'fairy', emoji: '🧚' },
  { name: 'vampire', emoji: '🧛' },
  { name: 'merperson', emoji: '🧜' },
  { name: 'elf', emoji: '🧝' },
  { name: 'genie', emoji: '🧞' },
  { name: 'zombie', emoji: '🧟' },

  // Hearts & symbols
  { name: 'heart', emoji: '❤️', aliases: ['love', 'red_heart'] },
  { name: 'orange_heart', emoji: '🧡' },
  { name: 'yellow_heart', emoji: '💛' },
  { name: 'green_heart', emoji: '💚' },
  { name: 'blue_heart', emoji: '💙' },
  { name: 'purple_heart', emoji: '💜' },
  { name: 'black_heart', emoji: '🖤' },
  { name: 'white_heart', emoji: '🤍' },
  { name: 'brown_heart', emoji: '🤎' },
  { name: 'broken_heart', emoji: '💔' },
  { name: 'heart_on_fire', emoji: '❤️‍🔥' },
  { name: 'mending_heart', emoji: '❤️‍🩹' },
  { name: 'two_hearts', emoji: '💕' },
  { name: 'revolving_hearts', emoji: '💞' },
  { name: 'heartbeat', emoji: '💓' },
  { name: 'heartpulse', emoji: '💗' },
  { name: 'sparkling_heart', emoji: '💖' },
  { name: 'cupid', emoji: '💘' },
  { name: 'gift_heart', emoji: '💝' },
  { name: 'heart_decoration', emoji: '💟' },
  { name: 'peace_symbol', emoji: '☮️' },
  { name: 'cross', emoji: '✝️' },
  { name: 'star_and_crescent', emoji: '☪️' },
  { name: 'om', emoji: '🕉️' },
  { name: 'wheel_of_dharma', emoji: '☸️' },
  { name: 'star_of_david', emoji: '✡️' },
  { name: 'six_pointed_star', emoji: '🔯' },
  { name: 'menorah', emoji: '🕎' },
  { name: 'yin_yang', emoji: '☯️' },
  { name: 'orthodox_cross', emoji: '☦️' },
  { name: 'place_of_worship', emoji: '🛐' },
  { name: 'ophiuchus', emoji: '⛎' },
  { name: 'aries', emoji: '♈' },
  { name: 'taurus', emoji: '♉' },
  { name: 'gemini', emoji: '♊' },
  { name: 'cancer', emoji: '♋' },
  { name: 'leo', emoji: '♌' },
  { name: 'virgo', emoji: '♍' },
  { name: 'libra', emoji: '♎' },
  { name: 'scorpius', emoji: '♏' },
  { name: 'sagittarius', emoji: '♐' },
  { name: 'capricorn', emoji: '♑' },
  { name: 'aquarius', emoji: '♒' },
  { name: 'pisces', emoji: '♓' },
  { name: 'id', emoji: '🆔' },
  { name: 'atom_symbol', emoji: '⚛️' },
  { name: 'accept', emoji: '🉑' },
  { name: 'radioactive', emoji: '☢️' },
  { name: 'biohazard', emoji: '☣️' },
  { name: 'mobile_phone_off', emoji: '📴' },
  { name: 'vibration_mode', emoji: '📳' },
  { name: 'u7a7a', emoji: '🈳' },
  { name: 'u5272', emoji: '🈹' },
  { name: 'u55b6', emoji: '🈺' },
  { name: 'u6709', emoji: '🈶' },
  { name: 'u7121', emoji: '🈚' },
  { name: 'u7533', emoji: '🈸' },
  { name: 'u7981', emoji: '🈲' },
  { name: 'ideograph_advantage', emoji: '🉐' },
  { name: 'u5408', emoji: '🈴' },
  { name: 'u6e80', emoji: '🈵' },
  { name: 'u6708', emoji: '🈷️' },
  { name: 'vs', emoji: '🆚' },
  { name: 'white_flower', emoji: '💮' },
  { name: 'anger', emoji: '💢' },
  { name: 'exclamation', emoji: '❗', aliases: ['heavy_exclamation_mark'] },
  { name: 'grey_exclamation', emoji: '❕' },
  { name: 'question', emoji: '❓' },
  { name: 'grey_question', emoji: '❔' },
  { name: 'bangbang', emoji: '‼️' },
  { name: 'interrobang', emoji: '⁉️' },
  { name: '100', emoji: '💯', aliases: ['hundred'] },
  { name: 'dizzy', emoji: '💫' },
  { name: 'dash', emoji: '💨' },
  { name: 'hole', emoji: '🕳️' },
  { name: 'bomb', emoji: '💣' },
  { name: 'speech_balloon', emoji: '💬', aliases: ['comment', 'chat'] },
  { name: 'eye_speech_bubble', emoji: '👁️‍🗨️' },
  { name: 'left_speech_bubble', emoji: '🗨️' },
  { name: 'right_anger_bubble', emoji: '🗯️' },
  { name: 'thought_balloon', emoji: '💭' },
  { name: 'zzz', emoji: '💤' },

  // Nature & animals
  { name: 'monkey_face', emoji: '🐵' },
  { name: 'monkey', emoji: '🐒' },
  { name: 'gorilla', emoji: '🦍' },
  { name: 'orangutan', emoji: '🦧' },
  { name: 'dog', emoji: '🐶', aliases: ['puppy'] },
  { name: 'dog2', emoji: '🐕' },
  { name: 'guide_dog', emoji: '🦮' },
  { name: 'poodle', emoji: '🐩' },
  { name: 'wolf', emoji: '🐺' },
  { name: 'fox_face', emoji: '🦊', aliases: ['fox'] },
  { name: 'raccoon', emoji: '🦝' },
  { name: 'cat', emoji: '🐱', aliases: ['kitty'] },
  { name: 'cat2', emoji: '🐈' },
  { name: 'lion', emoji: '🦁' },
  { name: 'tiger', emoji: '🐯' },
  { name: 'tiger2', emoji: '🐅' },
  { name: 'leopard', emoji: '🐆' },
  { name: 'horse', emoji: '🐴' },
  { name: 'racehorse', emoji: '🐎' },
  { name: 'unicorn', emoji: '🦄' },
  { name: 'zebra', emoji: '🦓' },
  { name: 'deer', emoji: '🦌' },
  { name: 'bison', emoji: '🦬' },
  { name: 'cow', emoji: '🐮' },
  { name: 'ox', emoji: '🐂' },
  { name: 'water_buffalo', emoji: '🐃' },
  { name: 'cow2', emoji: '🐄' },
  { name: 'pig', emoji: '🐷' },
  { name: 'pig2', emoji: '🐖' },
  { name: 'boar', emoji: '🐗' },
  { name: 'pig_nose', emoji: '🐽' },
  { name: 'ram', emoji: '🐏' },
  { name: 'sheep', emoji: '🐑' },
  { name: 'goat', emoji: '🐐' },
  { name: 'dromedary_camel', emoji: '🐪' },
  { name: 'camel', emoji: '🐫' },
  { name: 'llama', emoji: '🦙' },
  { name: 'giraffe', emoji: '🦒' },
  { name: 'elephant', emoji: '🐘' },
  { name: 'mammoth', emoji: '🦣' },
  { name: 'rhinoceros', emoji: '🦏' },
  { name: 'hippopotamus', emoji: '🦛' },
  { name: 'mouse', emoji: '🐭' },
  { name: 'mouse2', emoji: '🐁' },
  { name: 'rat', emoji: '🐀' },
  { name: 'hamster', emoji: '🐹' },
  { name: 'rabbit', emoji: '🐰' },
  { name: 'rabbit2', emoji: '🐇' },
  { name: 'chipmunk', emoji: '🐿️' },
  { name: 'beaver', emoji: '🦫' },
  { name: 'hedgehog', emoji: '🦔' },
  { name: 'bat', emoji: '🦇' },
  { name: 'bear', emoji: '🐻' },
  { name: 'polar_bear', emoji: '🐻‍❄️' },
  { name: 'koala', emoji: '🐨' },
  { name: 'panda_face', emoji: '🐼', aliases: ['panda'] },
  { name: 'sloth', emoji: '🦥' },
  { name: 'otter', emoji: '🦦' },
  { name: 'skunk', emoji: '🦨' },
  { name: 'kangaroo', emoji: '🦘' },
  { name: 'badger', emoji: '🦡' },
  { name: 'feet', emoji: '🐾', aliases: ['paw_prints'] },
  { name: 'turkey', emoji: '🦃' },
  { name: 'chicken', emoji: '🐔' },
  { name: 'rooster', emoji: '🐓' },
  { name: 'hatching_chick', emoji: '🐣' },
  { name: 'baby_chick', emoji: '🐤' },
  { name: 'hatched_chick', emoji: '🐥' },
  { name: 'bird', emoji: '🐦' },
  { name: 'penguin', emoji: '🐧' },
  { name: 'dove', emoji: '🕊️' },
  { name: 'eagle', emoji: '🦅' },
  { name: 'duck', emoji: '🦆' },
  { name: 'swan', emoji: '🦢' },
  { name: 'owl', emoji: '🦉' },
  { name: 'dodo', emoji: '🦤' },
  { name: 'feather', emoji: '🪶' },
  { name: 'flamingo', emoji: '🦩' },
  { name: 'peacock', emoji: '🦚' },
  { name: 'parrot', emoji: '🦜' },
  { name: 'frog', emoji: '🐸' },
  { name: 'crocodile', emoji: '🐊' },
  { name: 'turtle', emoji: '🐢' },
  { name: 'lizard', emoji: '🦎' },
  { name: 'snake', emoji: '🐍' },
  { name: 'dragon_face', emoji: '🐲' },
  { name: 'dragon', emoji: '🐉' },
  { name: 'sauropod', emoji: '🦕' },
  { name: 't_rex', emoji: '🦖' },
  { name: 'whale', emoji: '🐳' },
  { name: 'whale2', emoji: '🐋' },
  { name: 'dolphin', emoji: '🐬' },
  { name: 'seal', emoji: '🦭' },
  { name: 'fish', emoji: '🐟' },
  { name: 'tropical_fish', emoji: '🐠' },
  { name: 'blowfish', emoji: '🐡' },
  { name: 'shark', emoji: '🦈' },
  { name: 'octopus', emoji: '🐙' },
  { name: 'shell', emoji: '🐚' },
  { name: 'snail', emoji: '🐌' },
  { name: 'butterfly', emoji: '🦋' },
  { name: 'bug', emoji: '🐛' },
  { name: 'ant', emoji: '🐜' },
  { name: 'bee', emoji: '🐝', aliases: ['honeybee'] },
  { name: 'beetle', emoji: '🪲' },
  { name: 'lady_beetle', emoji: '🐞', aliases: ['ladybug'] },
  { name: 'cricket', emoji: '🦗' },
  { name: 'cockroach', emoji: '🪳' },
  { name: 'spider', emoji: '🕷️' },
  { name: 'spider_web', emoji: '🕸️' },
  { name: 'scorpion', emoji: '🦂' },
  { name: 'mosquito', emoji: '🦟' },
  { name: 'fly', emoji: '🪰' },
  { name: 'worm', emoji: '🪱' },
  { name: 'microbe', emoji: '🦠' },

  // Plants / weather
  { name: 'bouquet', emoji: '💐' },
  { name: 'cherry_blossom', emoji: '🌸' },
  { name: 'white_flower', emoji: '💮' },
  { name: 'rosette', emoji: '🏵️' },
  { name: 'rose', emoji: '🌹' },
  { name: 'wilted_flower', emoji: '🥀' },
  { name: 'hibiscus', emoji: '🌺' },
  { name: 'sunflower', emoji: '🌻' },
  { name: 'blossom', emoji: '🌼' },
  { name: 'tulip', emoji: '🌷' },
  { name: 'seedling', emoji: '🌱' },
  { name: 'potted_plant', emoji: '🪴' },
  { name: 'evergreen_tree', emoji: '🌲' },
  { name: 'deciduous_tree', emoji: '🌳' },
  { name: 'palm_tree', emoji: '🌴' },
  { name: 'cactus', emoji: '🌵' },
  { name: 'ear_of_rice', emoji: '🌾' },
  { name: 'herb', emoji: '🌿' },
  { name: 'shamrock', emoji: '☘️' },
  { name: 'four_leaf_clover', emoji: '🍀', aliases: ['clover', 'luck'] },
  { name: 'maple_leaf', emoji: '🍁' },
  { name: 'fallen_leaf', emoji: '🍂' },
  { name: 'leaves', emoji: '🍃' },
  { name: 'mushroom', emoji: '🍄' },
  { name: 'chestnut', emoji: '🌰' },
  { name: 'crab', emoji: '🦀' },
  { name: 'lobster', emoji: '🦞' },
  { name: 'shrimp', emoji: '🦐' },
  { name: 'squid', emoji: '🦑' },
  { name: 'globe_with_meridians', emoji: '🌐' },
  { name: 'rock', emoji: '🪨' },
  { name: 'new_moon', emoji: '🌑' },
  { name: 'waxing_crescent_moon', emoji: '🌒' },
  { name: 'first_quarter_moon', emoji: '🌓' },
  { name: 'moon', emoji: '🌔', aliases: ['waxing_gibbous_moon'] },
  { name: 'full_moon', emoji: '🌕' },
  { name: 'waning_gibbous_moon', emoji: '🌖' },
  { name: 'last_quarter_moon', emoji: '🌗' },
  { name: 'waning_crescent_moon', emoji: '🌘' },
  { name: 'crescent_moon', emoji: '🌙' },
  { name: 'new_moon_with_face', emoji: '🌚' },
  { name: 'first_quarter_moon_with_face', emoji: '🌛' },
  { name: 'last_quarter_moon_with_face', emoji: '🌜' },
  { name: 'sunny', emoji: '☀️', aliases: ['sun'] },
  { name: 'full_moon_with_face', emoji: '🌝' },
  { name: 'sun_with_face', emoji: '🌞' },
  { name: 'star', emoji: '⭐' },
  { name: 'star2', emoji: '🌟', aliases: ['glowing_star'] },
  { name: 'stars', emoji: '🌠' },
  { name: 'milky_way', emoji: '🌌' },
  { name: 'cloud', emoji: '☁️' },
  { name: 'partly_sunny', emoji: '⛅' },
  { name: 'cloud_with_lightning_and_rain', emoji: '⛈️' },
  { name: 'sun_behind_small_cloud', emoji: '🌤️' },
  { name: 'sun_behind_large_cloud', emoji: '🌥️' },
  { name: 'sun_behind_rain_cloud', emoji: '🌦️' },
  { name: 'cloud_with_rain', emoji: '🌧️', aliases: ['rain'] },
  { name: 'cloud_with_snow', emoji: '🌨️' },
  { name: 'cloud_with_lightning', emoji: '🌩️' },
  { name: 'tornado', emoji: '🌪️' },
  { name: 'fog', emoji: '🌫️' },
  { name: 'wind_face', emoji: '🌬️' },
  { name: 'cyclone', emoji: '🌀' },
  { name: 'rainbow', emoji: '🌈' },
  { name: 'closed_umbrella', emoji: '🌂' },
  { name: 'umbrella', emoji: '☂️' },
  { name: 'umbrella_with_rain_drops', emoji: '☔' },
  { name: 'umbrella_on_ground', emoji: '⛱️' },
  { name: 'zap', emoji: '⚡', aliases: ['lightning', 'voltage'] },
  { name: 'snowflake', emoji: '❄️', aliases: ['snow'] },
  { name: 'snowman', emoji: '⛄' },
  { name: 'snowman_with_snow', emoji: '☃️' },
  { name: 'comet', emoji: '☄️' },
  { name: 'fire', emoji: '🔥', aliases: ['flame', 'hot'] },
  { name: 'droplet', emoji: '💧' },
  { name: 'ocean', emoji: '🌊', aliases: ['wave'] },

  // Food
  { name: 'grapes', emoji: '🍇' },
  { name: 'melon', emoji: '🍈' },
  { name: 'watermelon', emoji: '🍉' },
  { name: 'tangerine', emoji: '🍊', aliases: ['orange'] },
  { name: 'lemon', emoji: '🍋' },
  { name: 'banana', emoji: '🍌' },
  { name: 'pineapple', emoji: '🍍' },
  { name: 'mango', emoji: '🥭' },
  { name: 'apple', emoji: '🍎', aliases: ['red_apple'] },
  { name: 'green_apple', emoji: '🍏' },
  { name: 'pear', emoji: '🍐' },
  { name: 'peach', emoji: '🍑' },
  { name: 'cherries', emoji: '🍒' },
  { name: 'strawberry', emoji: '🍓' },
  { name: 'blueberries', emoji: '🫐' },
  { name: 'kiwi_fruit', emoji: '🥝' },
  { name: 'tomato', emoji: '🍅' },
  { name: 'olive', emoji: '🫒' },
  { name: 'coconut', emoji: '🥥' },
  { name: 'avocado', emoji: '🥑' },
  { name: 'eggplant', emoji: '🍆' },
  { name: 'potato', emoji: '🥔' },
  { name: 'carrot', emoji: '🥕' },
  { name: 'corn', emoji: '🌽' },
  { name: 'hot_pepper', emoji: '🌶️', aliases: ['chili'] },
  { name: 'bell_pepper', emoji: '🫑' },
  { name: 'cucumber', emoji: '🥒' },
  { name: 'leafy_green', emoji: '🥬' },
  { name: 'broccoli', emoji: '🥦' },
  { name: 'garlic', emoji: '🧄' },
  { name: 'onion', emoji: '🧅' },
  { name: 'mushroom', emoji: '🍄' },
  { name: 'peanuts', emoji: '🥜' },
  { name: 'bread', emoji: '🍞' },
  { name: 'croissant', emoji: '🥐' },
  { name: 'baguette_bread', emoji: '🥖' },
  { name: 'flatbread', emoji: '🫓' },
  { name: 'pretzel', emoji: '🥨' },
  { name: 'bagel', emoji: '🥯' },
  { name: 'pancakes', emoji: '🥞' },
  { name: 'waffle', emoji: '🧇' },
  { name: 'cheese', emoji: '🧀' },
  { name: 'meat_on_bone', emoji: '🍖' },
  { name: 'poultry_leg', emoji: '🍗' },
  { name: 'cut_of_meat', emoji: '🥩' },
  { name: 'bacon', emoji: '🥓' },
  { name: 'hamburger', emoji: '🍔', aliases: ['burger'] },
  { name: 'fries', emoji: '🍟' },
  { name: 'pizza', emoji: '🍕' },
  { name: 'hotdog', emoji: '🌭' },
  { name: 'sandwich', emoji: '🥪' },
  { name: 'taco', emoji: '🌮' },
  { name: 'burrito', emoji: '🌯' },
  { name: 'tamale', emoji: '🫔' },
  { name: 'stuffed_flatbread', emoji: '🥙' },
  { name: 'falafel', emoji: '🧆' },
  { name: 'egg', emoji: '🥚' },
  { name: 'fried_egg', emoji: '🍳', aliases: ['cooking'] },
  { name: 'shallow_pan_of_food', emoji: '🥘' },
  { name: 'stew', emoji: '🍲' },
  { name: 'fondue', emoji: '🫕' },
  { name: 'bowl_with_spoon', emoji: '🥣' },
  { name: 'green_salad', emoji: '🥗' },
  { name: 'popcorn', emoji: '🍿' },
  { name: 'butter', emoji: '🧈' },
  { name: 'salt', emoji: '🧂' },
  { name: 'canned_food', emoji: '🥫' },
  { name: 'bento', emoji: '🍱' },
  { name: 'rice_cracker', emoji: '🍘' },
  { name: 'rice_ball', emoji: '🍙' },
  { name: 'rice', emoji: '🍚' },
  { name: 'curry', emoji: '🍛' },
  { name: 'ramen', emoji: '🍜' },
  { name: 'spaghetti', emoji: '🍝' },
  { name: 'sweet_potato', emoji: '🍠' },
  { name: 'oden', emoji: '🍢' },
  { name: 'sushi', emoji: '🍣' },
  { name: 'fried_shrimp', emoji: '🍤' },
  { name: 'fish_cake', emoji: '🍥' },
  { name: 'moon_cake', emoji: '🥮' },
  { name: 'dango', emoji: '🍡' },
  { name: 'dumpling', emoji: '🥟' },
  { name: 'fortune_cookie', emoji: '🥠' },
  { name: 'takeout_box', emoji: '🥡' },
  { name: 'oyster', emoji: '🦪' },
  { name: 'icecream', emoji: '🍦' },
  { name: 'shaved_ice', emoji: '🍧' },
  { name: 'ice_cream', emoji: '🍨' },
  { name: 'doughnut', emoji: '🍩', aliases: ['donut'] },
  { name: 'cookie', emoji: '🍪' },
  { name: 'birthday', emoji: '🎂', aliases: ['cake'] },
  { name: 'cake', emoji: '🍰', aliases: ['shortcake'] },
  { name: 'cupcake', emoji: '🧁' },
  { name: 'pie', emoji: '🥧' },
  { name: 'chocolate_bar', emoji: '🍫' },
  { name: 'candy', emoji: '🍬' },
  { name: 'lollipop', emoji: '🍭' },
  { name: 'custard', emoji: '🍮' },
  { name: 'honey_pot', emoji: '🍯' },
  { name: 'baby_bottle', emoji: '🍼' },
  { name: 'milk_glass', emoji: '🥛' },
  { name: 'coffee', emoji: '☕' },
  { name: 'teapot', emoji: '🫖' },
  { name: 'tea', emoji: '🍵' },
  { name: 'sake', emoji: '🍶' },
  { name: 'champagne', emoji: '🍾' },
  { name: 'wine_glass', emoji: '🍷' },
  { name: 'cocktail', emoji: '🍸' },
  { name: 'tropical_drink', emoji: '🍹' },
  { name: 'beer', emoji: '🍺' },
  { name: 'beers', emoji: '🍻' },
  { name: 'clinking_glasses', emoji: '🥂' },
  { name: 'tumbler_glass', emoji: '🥃' },
  { name: 'cup_with_straw', emoji: '🥤' },
  { name: 'bubble_tea', emoji: '🧋' },
  { name: 'beverage_box', emoji: '🧃' },
  { name: 'mate', emoji: '🧉' },
  { name: 'ice_cube', emoji: '🧊' },

  // Activities / objects
  { name: 'soccer', emoji: '⚽', aliases: ['football'] },
  { name: 'basketball', emoji: '🏀' },
  { name: 'football', emoji: '🏈', aliases: ['american_football'] },
  { name: 'baseball', emoji: '⚾' },
  { name: 'softball', emoji: '🥎' },
  { name: 'tennis', emoji: '🎾' },
  { name: 'volleyball', emoji: '🏐' },
  { name: 'rugby_football', emoji: '🏉' },
  { name: 'flying_disc', emoji: '🥏' },
  { name: '8ball', emoji: '🎱' },
  { name: 'yo_yo', emoji: '🪀' },
  { name: 'ping_pong', emoji: '🏓' },
  { name: 'badminton', emoji: '🏸' },
  { name: 'hockey', emoji: '🏒' },
  { name: 'field_hockey', emoji: '🏑' },
  { name: 'lacrosse', emoji: '🥍' },
  { name: 'cricket_game', emoji: '🏏' },
  { name: 'goal_net', emoji: '🥅' },
  { name: 'golf', emoji: '⛳' },
  { name: 'bow_and_arrow', emoji: '🏹' },
  { name: 'fishing_pole_and_fish', emoji: '🎣' },
  { name: 'diving_mask', emoji: '🤿' },
  { name: 'boxing_glove', emoji: '🥊' },
  { name: 'martial_arts_uniform', emoji: '🥋' },
  { name: 'running_shirt_with_sash', emoji: '🎽' },
  { name: 'skateboard', emoji: '🛹' },
  { name: 'roller_skate', emoji: '🛼' },
  { name: 'sled', emoji: '🛷' },
  { name: 'ice_skate', emoji: '⛸️' },
  { name: 'curling_stone', emoji: '🥌' },
  { name: 'ski', emoji: '🎿' },
  { name: 'skier', emoji: '⛷️' },
  { name: 'snowboarder', emoji: '🏂' },
  { name: 'parachute', emoji: '🪂' },
  { name: 'person_lifting_weights', emoji: '🏋️', aliases: ['gym', 'weights'] },
  { name: 'person_fencing', emoji: '🤺' },
  { name: 'wrestling', emoji: '🤼' },
  { name: 'person_doing_cartwheel', emoji: '🤸' },
  { name: 'person_playing_water_polo', emoji: '🤽' },
  { name: 'person_playing_handball', emoji: '🤾' },
  { name: 'person_juggling', emoji: '🤹' },
  { name: 'yoga', emoji: '🧘', aliases: ['lotus', 'meditation'] },
  { name: 'trophy', emoji: '🏆', aliases: ['win', 'champion'] },
  { name: 'medal_sports', emoji: '🏅' },
  { name: '1st_place_medal', emoji: '🥇', aliases: ['gold'] },
  { name: '2nd_place_medal', emoji: '🥈', aliases: ['silver'] },
  { name: '3rd_place_medal', emoji: '🥉', aliases: ['bronze'] },
  { name: 'medal_military', emoji: '🎖️' },
  { name: 'rosette', emoji: '🏵️' },
  { name: 'reminder_ribbon', emoji: '🎗️' },
  { name: 'ticket', emoji: '🎫' },
  { name: 'tickets', emoji: '🎟️' },
  { name: 'circus_tent', emoji: '🎪' },
  { name: 'juggling', emoji: '🤹' },
  { name: 'performing_arts', emoji: '🎭' },
  { name: 'ballet_shoes', emoji: '🩰' },
  { name: 'art', emoji: '🎨', aliases: ['palette'] },
  { name: 'clapper', emoji: '🎬' },
  { name: 'microphone', emoji: '🎤' },
  { name: 'headphones', emoji: '🎧' },
  { name: 'musical_score', emoji: '🎼' },
  { name: 'musical_keyboard', emoji: '🎹' },
  { name: 'drum', emoji: '🥁' },
  { name: 'long_drum', emoji: '🪘' },
  { name: 'saxophone', emoji: '🎷' },
  { name: 'trumpet', emoji: '🎺' },
  { name: 'guitar', emoji: '🎸' },
  { name: 'banjo', emoji: '🪕' },
  { name: 'violin', emoji: '🎻' },
  { name: 'game_die', emoji: '🎲', aliases: ['dice'] },
  { name: 'chess_pawn', emoji: '♟️' },
  { name: 'dart', emoji: '🎯', aliases: ['target', 'direct_hit'] },
  { name: 'bowling', emoji: '🎳' },
  { name: 'video_game', emoji: '🎮', aliases: ['controller', 'game'] },
  { name: 'slot_machine', emoji: '🎰' },
  { name: 'jigsaw', emoji: '🧩', aliases: ['puzzle'] },

  // Travel / places
  { name: 'car', emoji: '🚗', aliases: ['red_car'] },
  { name: 'taxi', emoji: '🚕' },
  { name: 'blue_car', emoji: '🚙' },
  { name: 'bus', emoji: '🚌' },
  { name: 'trolleybus', emoji: '🚎' },
  { name: 'racing_car', emoji: '🏎️' },
  { name: 'police_car', emoji: '🚓' },
  { name: 'ambulance', emoji: '🚑' },
  { name: 'fire_engine', emoji: '🚒' },
  { name: 'minibus', emoji: '🚐' },
  { name: 'truck', emoji: '🚚' },
  { name: 'articulated_lorry', emoji: '🚛' },
  { name: 'tractor', emoji: '🚜' },
  { name: 'kick_scooter', emoji: '🛴' },
  { name: 'bike', emoji: '🚲', aliases: ['bicycle'] },
  { name: 'motor_scooter', emoji: '🛵' },
  { name: 'motorcycle', emoji: '🏍️' },
  { name: 'auto_rickshaw', emoji: '🛺' },
  { name: 'rotating_light', emoji: '🚨' },
  { name: 'oncoming_police_car', emoji: '🚔' },
  { name: 'oncoming_bus', emoji: '🚍' },
  { name: 'oncoming_automobile', emoji: '🚘' },
  { name: 'oncoming_taxi', emoji: '🚖' },
  { name: 'aerial_tramway', emoji: '🚡' },
  { name: 'mountain_cableway', emoji: '🚠' },
  { name: 'suspension_railway', emoji: '🚟' },
  { name: 'railway_car', emoji: '🚃' },
  { name: 'train', emoji: '🚋' },
  { name: 'monorail', emoji: '🚝' },
  { name: 'bullettrain_side', emoji: '🚄' },
  { name: 'bullettrain_front', emoji: '🚅' },
  { name: 'light_rail', emoji: '🚈' },
  { name: 'mountain_railway', emoji: '🚞' },
  { name: 'steam_locomotive', emoji: '🚂' },
  { name: 'train2', emoji: '🚆' },
  { name: 'metro', emoji: '🚇' },
  { name: 'tram', emoji: '🚊' },
  { name: 'station', emoji: '🚉' },
  { name: 'airplane', emoji: '✈️', aliases: ['flight', 'plane'] },
  { name: 'flight_departure', emoji: '🛫' },
  { name: 'flight_arrival', emoji: '🛬' },
  { name: 'parachute', emoji: '🪂' },
  { name: 'seat', emoji: '💺' },
  { name: 'helicopter', emoji: '🚁' },
  { name: 'suspension_railway', emoji: '🚟' },
  { name: 'mountain_cableway', emoji: '🚠' },
  { name: 'aerial_tramway', emoji: '🚡' },
  { name: 'satellite', emoji: '🛰️' },
  { name: 'rocket', emoji: '🚀', aliases: ['ship', 'launch'] },
  { name: 'flying_saucer', emoji: '🛸' },
  { name: 'bellhop_bell', emoji: '🛎️' },
  { name: 'luggage', emoji: '🧳' },
  { name: 'hourglass', emoji: '⌛' },
  { name: 'hourglass_flowing_sand', emoji: '⏳' },
  { name: 'watch', emoji: '⌚' },
  { name: 'alarm_clock', emoji: '⏰' },
  { name: 'stopwatch', emoji: '⏱️' },
  { name: 'timer_clock', emoji: '⏲️' },
  { name: 'mantelpiece_clock', emoji: '🕰️' },
  { name: 'clock12', emoji: '🕛' },
  { name: 'clock1230', emoji: '🕧' },
  { name: 'clock1', emoji: '🕐' },
  { name: 'clock130', emoji: '🕜' },
  { name: 'clock2', emoji: '🕑' },
  { name: 'clock230', emoji: '🕝' },
  { name: 'clock3', emoji: '🕒' },
  { name: 'clock330', emoji: '🕞' },
  { name: 'clock4', emoji: '🕓' },
  { name: 'clock430', emoji: '🕟' },
  { name: 'clock5', emoji: '🕔' },
  { name: 'clock530', emoji: '🕠' },
  { name: 'clock6', emoji: '🕕' },
  { name: 'clock630', emoji: '🕡' },
  { name: 'clock7', emoji: '🕖' },
  { name: 'clock730', emoji: '🕢' },
  { name: 'clock8', emoji: '🕗' },
  { name: 'clock830', emoji: '🕣' },
  { name: 'clock9', emoji: '🕘' },
  { name: 'clock930', emoji: '🕤' },
  { name: 'clock10', emoji: '🕙' },
  { name: 'clock1030', emoji: '🕥' },
  { name: 'clock11', emoji: '🕚' },
  { name: 'clock1130', emoji: '🕦' },

  // Objects / work
  { name: 'phone', emoji: '☎️' },
  { name: 'calling', emoji: '📲' },
  { name: 'iphone', emoji: '📱', aliases: ['mobile', 'smartphone'] },
  { name: 'computer', emoji: '💻', aliases: ['laptop'] },
  { name: 'desktop_computer', emoji: '🖥️' },
  { name: 'printer', emoji: '🖨️' },
  { name: 'keyboard', emoji: '⌨️' },
  { name: 'computer_mouse', emoji: '🖱️' },
  { name: 'trackball', emoji: '🖲️' },
  { name: 'joystick', emoji: '🕹️' },
  { name: 'clamp', emoji: '🗜️' },
  { name: 'minidisc', emoji: '💽' },
  { name: 'floppy_disk', emoji: '💾' },
  { name: 'cd', emoji: '💿' },
  { name: 'dvd', emoji: '📀' },
  { name: 'abacus', emoji: '🧮' },
  { name: 'movie_camera', emoji: '🎥' },
  { name: 'film_strip', emoji: '🎞️' },
  { name: 'film_projector', emoji: '📽️' },
  { name: 'clapper', emoji: '🎬' },
  { name: 'tv', emoji: '📺' },
  { name: 'camera', emoji: '📷' },
  { name: 'camera_flash', emoji: '📸' },
  { name: 'video_camera', emoji: '📹' },
  { name: 'vhs', emoji: '📼' },
  { name: 'mag', emoji: '🔍', aliases: ['search'] },
  { name: 'mag_right', emoji: '🔎' },
  { name: 'candle', emoji: '🕯️' },
  { name: 'bulb', emoji: '💡', aliases: ['idea', 'light'] },
  { name: 'flashlight', emoji: '🔦' },
  { name: 'izakaya_lantern', emoji: '🏮' },
  { name: 'diya_lamp', emoji: '🪔' },
  { name: 'notebook_with_decorative_cover', emoji: '📔' },
  { name: 'closed_book', emoji: '📕' },
  { name: 'book', emoji: '📖', aliases: ['open_book'] },
  { name: 'green_book', emoji: '📗' },
  { name: 'blue_book', emoji: '📘' },
  { name: 'orange_book', emoji: '📙' },
  { name: 'books', emoji: '📚' },
  { name: 'notebook', emoji: '📓' },
  { name: 'ledger', emoji: '📒' },
  { name: 'page_with_curl', emoji: '📃' },
  { name: 'scroll', emoji: '📜' },
  { name: 'page_facing_up', emoji: '📄' },
  { name: 'newspaper', emoji: '📰' },
  { name: 'newspaper_roll', emoji: '🗞️' },
  { name: 'bookmark_tabs', emoji: '📑' },
  { name: 'bookmark', emoji: '🔖' },
  { name: 'label', emoji: '🏷️' },
  { name: 'moneybag', emoji: '💰', aliases: ['money'] },
  { name: 'coin', emoji: '🪙' },
  { name: 'yen', emoji: '💴' },
  { name: 'dollar', emoji: '💵' },
  { name: 'euro', emoji: '💶' },
  { name: 'pound', emoji: '💷' },
  { name: 'money_with_wings', emoji: '💸' },
  { name: 'credit_card', emoji: '💳' },
  { name: 'receipt', emoji: '🧾' },
  { name: 'chart', emoji: '💹' },
  { name: 'email', emoji: '✉️', aliases: ['envelope'] },
  { name: 'e-mail', emoji: '📧' },
  { name: 'incoming_envelope', emoji: '📨' },
  { name: 'envelope_with_arrow', emoji: '📩' },
  { name: 'outbox_tray', emoji: '📤' },
  { name: 'inbox_tray', emoji: '📥' },
  { name: 'package', emoji: '📦', aliases: ['box'] },
  { name: 'mailbox', emoji: '📫' },
  { name: 'mailbox_closed', emoji: '📪' },
  { name: 'mailbox_with_mail', emoji: '📬' },
  { name: 'mailbox_with_no_mail', emoji: '📭' },
  { name: 'postbox', emoji: '📮' },
  { name: 'ballot_box', emoji: '🗳️' },
  { name: 'pencil2', emoji: '✏️', aliases: ['pencil'] },
  { name: 'black_nib', emoji: '✒️' },
  { name: 'fountain_pen', emoji: '🖋️' },
  { name: 'pen', emoji: '🖊️' },
  { name: 'paintbrush', emoji: '🖌️' },
  { name: 'crayon', emoji: '🖍️' },
  { name: 'memo', emoji: '📝', aliases: ['pencil', 'note'] },
  { name: 'briefcase', emoji: '💼' },
  { name: 'file_folder', emoji: '📁' },
  { name: 'open_file_folder', emoji: '📂' },
  { name: 'card_index_dividers', emoji: '🗂️' },
  { name: 'date', emoji: '📅', aliases: ['calendar'] },
  { name: 'calendar', emoji: '📆' },
  { name: 'spiral_notepad', emoji: '🗒️' },
  { name: 'spiral_calendar', emoji: '🗓️' },
  { name: 'card_index', emoji: '📇' },
  { name: 'chart_with_upwards_trend', emoji: '📈', aliases: ['chart_up', 'growth'] },
  { name: 'chart_with_downwards_trend', emoji: '📉', aliases: ['chart_down'] },
  { name: 'bar_chart', emoji: '📊' },
  { name: 'clipboard', emoji: '📋' },
  { name: 'pushpin', emoji: '📌', aliases: ['pin'] },
  { name: 'round_pushpin', emoji: '📍' },
  { name: 'paperclip', emoji: '📎' },
  { name: 'paperclips', emoji: '🖇️' },
  { name: 'straight_ruler', emoji: '📏' },
  { name: 'triangular_ruler', emoji: '📐' },
  { name: 'scissors', emoji: '✂️' },
  { name: 'card_file_box', emoji: '🗃️' },
  { name: 'file_cabinet', emoji: '🗄️' },
  { name: 'wastebasket', emoji: '🗑️', aliases: ['trash', 'bin'] },
  { name: 'lock', emoji: '🔒' },
  { name: 'unlock', emoji: '🔓' },
  { name: 'lock_with_ink_pen', emoji: '🔏' },
  { name: 'closed_lock_with_key', emoji: '🔐' },
  { name: 'key', emoji: '🔑' },
  { name: 'old_key', emoji: '🗝️' },
  { name: 'hammer', emoji: '🔨' },
  { name: 'axe', emoji: '🪓' },
  { name: 'pick', emoji: '⛏️' },
  { name: 'hammer_and_pick', emoji: '⚒️' },
  { name: 'hammer_and_wrench', emoji: '🛠️', aliases: ['tools'] },
  { name: 'dagger', emoji: '🗡️' },
  { name: 'crossed_swords', emoji: '⚔️' },
  { name: 'gun', emoji: '🔫', aliases: ['pistol'] },
  { name: 'boomerang', emoji: '🪃' },
  { name: 'bow_and_arrow', emoji: '🏹' },
  { name: 'shield', emoji: '🛡️' },
  { name: 'carpentry_saw', emoji: '🪚' },
  { name: 'wrench', emoji: '🔧' },
  { name: 'screwdriver', emoji: '🪛' },
  { name: 'nut_and_bolt', emoji: '🔩' },
  { name: 'gear', emoji: '⚙️', aliases: ['settings'] },
  { name: 'clamp', emoji: '🗜️' },
  { name: 'balance_scale', emoji: '⚖️' },
  { name: 'probing_cane', emoji: '🦯' },
  { name: 'link', emoji: '🔗' },
  { name: 'chains', emoji: '⛓️' },
  { name: 'hook', emoji: '🪝' },
  { name: 'toolbox', emoji: '🧰' },
  { name: 'magnet', emoji: '🧲' },
  { name: 'ladder', emoji: '🪜' },
  { name: 'alembic', emoji: '⚗️' },
  { name: 'test_tube', emoji: '🧪', aliases: ['science'] },
  { name: 'petri_dish', emoji: '🧫' },
  { name: 'dna', emoji: '🧬' },
  { name: 'microscope', emoji: '🔬' },
  { name: 'telescope', emoji: '🔭' },
  { name: 'satellite', emoji: '📡' },
  { name: 'syringe', emoji: '💉' },
  { name: 'drop_of_blood', emoji: '🩸' },
  { name: 'pill', emoji: '💊' },
  { name: 'adhesive_bandage', emoji: '🩹' },
  { name: 'stethoscope', emoji: '🩺' },
  { name: 'door', emoji: '🚪' },
  { name: 'elevator', emoji: '🛗' },
  { name: 'mirror', emoji: '🪞' },
  { name: 'window', emoji: '🪟' },
  { name: 'bed', emoji: '🛏️' },
  { name: 'couch_and_lamp', emoji: '🛋️' },
  { name: 'chair', emoji: '🪑' },
  { name: 'toilet', emoji: '🚽' },
  { name: 'plunger', emoji: '🪠' },
  { name: 'shower', emoji: '🚿' },
  { name: 'bathtub', emoji: '🛁' },
  { name: 'mouse_trap', emoji: '🪤' },
  { name: 'razor', emoji: '🪒' },
  { name: 'lotion_bottle', emoji: '🧴' },
  { name: 'safety_pin', emoji: '🧷' },
  { name: 'broom', emoji: '🧹' },
  { name: 'basket', emoji: '🧺' },
  { name: 'roll_of_paper', emoji: '🧻' },
  { name: 'bucket', emoji: '🪣' },
  { name: 'soap', emoji: '🧼' },
  { name: 'toothbrush', emoji: '🪥' },
  { name: 'sponge', emoji: '🧽' },
  { name: 'fire_extinguisher', emoji: '🧯' },
  { name: 'shopping_cart', emoji: '🛒' },
  { name: 'smoking', emoji: '🚬' },
  { name: 'coffin', emoji: '⚰️' },
  { name: 'headstone', emoji: '🪦' },
  { name: 'funeral_urn', emoji: '⚱️' },
  { name: 'moyai', emoji: '🗿' },
  { name: 'placard', emoji: '🪧' },

  // Flags & misc UI
  { name: 'checkered_flag', emoji: '🏁' },
  { name: 'triangular_flag_on_post', emoji: '🚩' },
  { name: 'crossed_flags', emoji: '🎌' },
  { name: 'black_flag', emoji: '🏴' },
  { name: 'white_flag', emoji: '🏳️' },
  { name: 'rainbow_flag', emoji: '🏳️‍🌈' },
  { name: 'transgender_flag', emoji: '🏳️‍⚧️' },
  { name: 'pirate_flag', emoji: '🏴‍☠️' },
  { name: 'check', emoji: '✅', aliases: ['white_check_mark', 'done'] },
  { name: 'ballot_box_with_check', emoji: '☑️' },
  { name: 'heavy_check_mark', emoji: '✔️' },
  { name: 'x', emoji: '❌', aliases: ['cross', 'no'] },
  { name: 'negative_squared_cross_mark', emoji: '❎' },
  { name: 'heavy_plus_sign', emoji: '➕', aliases: ['plus'] },
  { name: 'heavy_minus_sign', emoji: '➖', aliases: ['minus'] },
  { name: 'heavy_division_sign', emoji: '➗' },
  { name: 'curly_loop', emoji: '➰' },
  { name: 'loop', emoji: '➿' },
  { name: 'part_alternation_mark', emoji: '〽️' },
  { name: 'eight_spoked_asterisk', emoji: '✳️' },
  { name: 'eight_pointed_black_star', emoji: '✴️' },
  { name: 'sparkle', emoji: '❇️' },
  { name: 'bangbang', emoji: '‼️' },
  { name: 'interrobang', emoji: '⁉️' },
  { name: 'question', emoji: '❓' },
  { name: 'grey_question', emoji: '❔' },
  { name: 'grey_exclamation', emoji: '❕' },
  { name: 'exclamation', emoji: '❗' },
  { name: 'wavy_dash', emoji: '〰️' },
  { name: 'copyright', emoji: '©️' },
  { name: 'registered', emoji: '®️' },
  { name: 'tm', emoji: '™️' },
  { name: 'hash', emoji: '#️⃣' },
  { name: 'asterisk', emoji: '*️⃣' },
  { name: 'zero', emoji: '0️⃣' },
  { name: 'one', emoji: '1️⃣' },
  { name: 'two', emoji: '2️⃣' },
  { name: 'three', emoji: '3️⃣' },
  { name: 'four', emoji: '4️⃣' },
  { name: 'five', emoji: '5️⃣' },
  { name: 'six', emoji: '6️⃣' },
  { name: 'seven', emoji: '7️⃣' },
  { name: 'eight', emoji: '8️⃣' },
  { name: 'nine', emoji: '9️⃣' },
  { name: 'keycap_ten', emoji: '🔟' },
  { name: 'capital_abcd', emoji: '🔠' },
  { name: 'abcd', emoji: '🔡' },
  { name: '1234', emoji: '🔢' },
  { name: 'symbols', emoji: '🔣' },
  { name: 'abc', emoji: '🔤' },
  { name: 'a', emoji: '🅰️' },
  { name: 'ab', emoji: '🆎' },
  { name: 'b', emoji: '🅱️' },
  { name: 'cl', emoji: '🆑' },
  { name: 'o2', emoji: '🅾️' },
  { name: 'sos', emoji: '🆘' },
  { name: 'x', emoji: '❌' },
  { name: 'o', emoji: '⭕' },
  { name: 'stop_sign', emoji: '🛑', aliases: ['stop'] },
  { name: 'no_entry', emoji: '⛔' },
  { name: 'name_badge', emoji: '📛' },
  { name: 'no_entry_sign', emoji: '🚫' },
  { name: 'sparkles', emoji: '✨', aliases: ['shine', 'magic'] },
  { name: 'tada', emoji: '🎉', aliases: ['party', 'celebration', 'confetti'] },
  { name: 'confetti_ball', emoji: '🎊' },
  { name: 'balloon', emoji: '🎈' },
  { name: 'gift', emoji: '🎁', aliases: ['present'] },
  { name: 'ribbon', emoji: '🎀' },
  { name: 'warning', emoji: '⚠️' },
  { name: 'children_crossing', emoji: '🚸' },
  { name: 'no_pedestrians', emoji: '🚷' },
  { name: 'no_bicycles', emoji: '🚳' },
  { name: 'no_mobile_phones', emoji: '📵' },
  { name: 'underage', emoji: '🔞' },
  { name: 'radioactive', emoji: '☢️' },
  { name: 'biohazard', emoji: '☣️' },
  { name: 'arrow_up', emoji: '⬆️' },
  { name: 'arrow_upper_right', emoji: '↗️' },
  { name: 'arrow_right', emoji: '➡️' },
  { name: 'arrow_lower_right', emoji: '↘️' },
  { name: 'arrow_down', emoji: '⬇️' },
  { name: 'arrow_lower_left', emoji: '↙️' },
  { name: 'arrow_left', emoji: '⬅️' },
  { name: 'arrow_upper_left', emoji: '↖️' },
  { name: 'arrow_up_down', emoji: '↕️' },
  { name: 'left_right_arrow', emoji: '↔️' },
  { name: 'leftwards_arrow_with_hook', emoji: '↩️' },
  { name: 'arrow_right_hook', emoji: '↪️' },
  { name: 'arrow_heading_up', emoji: '⤴️' },
  { name: 'arrow_heading_down', emoji: '⤵️' },
  { name: 'arrows_clockwise', emoji: '🔃' },
  { name: 'arrows_counterclockwise', emoji: '🔄', aliases: ['refresh', 'reload'] },
  { name: 'back', emoji: '🔙' },
  { name: 'end', emoji: '🔚' },
  { name: 'on', emoji: '🔛' },
  { name: 'soon', emoji: '🔜' },
  { name: 'top', emoji: '🔝' },
  { name: 'place_of_worship', emoji: '🛐' },
  { name: 'atom_symbol', emoji: '⚛️' },
  { name: 'om', emoji: '🕉️' },
  { name: 'star_of_david', emoji: '✡️' },
  { name: 'wheel_of_dharma', emoji: '☸️' },
  { name: 'yin_yang', emoji: '☯️' },
  { name: 'latin_cross', emoji: '✝️' },
  { name: 'orthodox_cross', emoji: '☦️' },
  { name: 'star_and_crescent', emoji: '☪️' },
  { name: 'peace_symbol', emoji: '☮️' },
  { name: 'menorah', emoji: '🕎' },
  { name: 'six_pointed_star', emoji: '🔯' },
  { name: 'aries', emoji: '♈' },
  { name: 'taurus', emoji: '♉' },
  { name: 'gemini', emoji: '♊' },
  { name: 'cancer', emoji: '♋' },
  { name: 'leo', emoji: '♌' },
  { name: 'virgo', emoji: '♍' },
  { name: 'libra', emoji: '♎' },
  { name: 'scorpius', emoji: '♏' },
  { name: 'sagittarius', emoji: '♐' },
  { name: 'capricorn', emoji: '♑' },
  { name: 'aquarius', emoji: '♒' },
  { name: 'pisces', emoji: '♓' },
  { name: 'ophiuchus', emoji: '⛎' },
  { name: 'twisted_rightwards_arrows', emoji: '🔀' },
  { name: 'repeat', emoji: '🔁' },
  { name: 'repeat_one', emoji: '🔂' },
  { name: 'arrow_forward', emoji: '▶️' },
  { name: 'fast_forward', emoji: '⏩' },
  { name: 'next_track_button', emoji: '⏭️' },
  { name: 'play_or_pause_button', emoji: '⏯️' },
  { name: 'arrow_backward', emoji: '◀️' },
  { name: 'rewind', emoji: '⏪' },
  { name: 'previous_track_button', emoji: '⏮️' },
  { name: 'arrow_up_small', emoji: '🔼' },
  { name: 'arrow_double_up', emoji: '⏫' },
  { name: 'arrow_down_small', emoji: '🔽' },
  { name: 'arrow_double_down', emoji: '⏬' },
  { name: 'pause_button', emoji: '⏸️' },
  { name: 'stop_button', emoji: '⏹️' },
  { name: 'record_button', emoji: '⏺️' },
  { name: 'eject_button', emoji: '⏏️' },
  { name: 'cinema', emoji: '🎦' },
  { name: 'low_brightness', emoji: '🔅' },
  { name: 'high_brightness', emoji: '🔆' },
  { name: 'signal_strength', emoji: '📶' },
  { name: 'vibration_mode', emoji: '📳' },
  { name: 'mobile_phone_off', emoji: '📴' },
  { name: 'female_sign', emoji: '♀️' },
  { name: 'male_sign', emoji: '♂️' },
  { name: 'transgender_symbol', emoji: '⚧️' },
  { name: 'heavy_multiplication_x', emoji: '✖️' },
  { name: 'heavy_plus_sign', emoji: '➕' },
  { name: 'heavy_minus_sign', emoji: '➖' },
  { name: 'heavy_division_sign', emoji: '➗' },
  { name: 'infinity', emoji: '♾️' },
  { name: 'bangbang', emoji: '‼️' },
  { name: 'interrobang', emoji: '⁉️' },
  { name: 'question', emoji: '❓' },
  { name: 'grey_question', emoji: '❔' },
  { name: 'grey_exclamation', emoji: '❕' },
  { name: 'exclamation', emoji: '❗' },
  { name: 'wavy_dash', emoji: '〰️' },
  { name: 'currency_exchange', emoji: '💱' },
  { name: 'heavy_dollar_sign', emoji: '💲' },
  { name: 'medical_symbol', emoji: '⚕️' },
  { name: 'recycle', emoji: '♻️' },
  { name: 'fleur_de_lis', emoji: '⚜️' },
  { name: 'trident', emoji: '🔱' },
  { name: 'name_badge', emoji: '📛' },
  { name: 'beginner', emoji: '🔰' },
  { name: 'o', emoji: '⭕' },
  { name: 'white_check_mark', emoji: '✅' },
  { name: 'ballot_box_with_check', emoji: '☑️' },
  { name: 'heavy_check_mark', emoji: '✔️' },
  { name: 'x', emoji: '❌' },
  { name: 'negative_squared_cross_mark', emoji: '❎' },
  { name: 'curly_loop', emoji: '➰' },
  { name: 'loop', emoji: '➿' },
  { name: 'part_alternation_mark', emoji: '〽️' },
  { name: 'eight_spoked_asterisk', emoji: '✳️' },
  { name: 'eight_pointed_black_star', emoji: '✴️' },
  { name: 'sparkle', emoji: '❇️' },
  { name: 'copyright', emoji: '©️' },
  { name: 'registered', emoji: '®️' },
  { name: 'tm', emoji: '™️' },
]

/** Deduped searchable index (name + aliases). */
export function searchEmojis(query: string, limit = 40): EmojiEntry[] {
  const q = query.trim().toLowerCase().replace(/^:+|:+$/g, '')
  if (!q) {
    // Default suggestions when only ":" typed.
    return EMOJI_CATALOG.slice(0, limit)
  }

  const starts: EmojiEntry[] = []
  const includes: EmojiEntry[] = []
  const seen = new Set<string>()

  for (const entry of EMOJI_CATALOG) {
    const key = `${entry.emoji}:${entry.name}`
    if (seen.has(key)) continue

    const tokens = [entry.name, ...(entry.aliases ?? [])]
    const startHit = tokens.some((t) => t.startsWith(q))
    const includeHit = !startHit && tokens.some((t) => t.includes(q))

    if (startHit) {
      seen.add(key)
      starts.push(entry)
    } else if (includeHit) {
      seen.add(key)
      includes.push(entry)
    }

    if (starts.length >= limit) break
  }

  return [...starts, ...includes].slice(0, limit)
}
